ods html; 
ods listing close; 
ods graphics on; 
libname chapter3 'c:\Library_timeseries';
Data chapter3.example35_3 (keep=t price1);
       set chapter3.example35;
       if t=1 then delete;
       price1=price;
       t=t-1; 
run;  
Data chapter3.example35_4;
       merge chapter3.example35 chapter3.example35_3;
	   by t;
       delta=price1-price; 
run;  
Data chapter3.example35_5 (keep=t delta1);
set chapter3.example35_4;
if t=1 then delete;
delta1=delta;
t=t-1; 
run;  
Data chapter3.example35_6;
       merge chapter3.example35_4 chapter3.example35_5;
	   by t;
       delta2=delta1-delta; 
run;  
Proc gplot data= chapter3.example35_4; 
      symbol i=spline v=circle h=1.5; 
      plot delta * t; 
       title 'Difference plot of gold price data during 2005';
   run;
Proc gplot data= chapter3.example35_6; 
      symbol i=spline v=circle h=1.5; 
      plot delta2 * t; 
      title 'The second-order difference plot of gold price data during 2005';
   run;


ods graphics off;
ods html close;
ods listing;
