ods html; 
ods listing close; 
ods graphics on; 
libname TS3 'c:\Library_timeseries';

Data TS3.example35;
infile 'C:\Data_CC\gold.dat';
input price;
if _N_<2 then delete;
t=_N_;
q=t*t;
run;
Proc gplot data= TS3.example35; 
      symbol i=spline v=circle h=1; 
      title 'Time plot of gold price';
	  plot price * t;
   run;
proc reg data=TS3.example35;
   model price=t q;
title 'Regression analysis of gold price';
run;
Data TS3.example35_1;
set TS3.example35;
y2=434.60058-0.36184*t+0.00264*q;
residual2=price-y2; 
run;  
Proc gplot data= TS3.example35_1;
      title 'Quadratic regression fit plot of gold price'; 
      symbol i=spline v=circle h=1; 
      plot price * t y2 * t/overlay;
   run;
   title 'Residual plot';
   plot residual2*t;
   run;
Proc autoreg data=TS3.example35_1;
      model residual2=t/dwprob;
run;
Data TS3.example35_2;
set TS3.example35_1;
price1=lag(price);
delta1=price-price1;
run;
Proc gplot data=TS3.example35_2; 
 plot delta1*t;
 run;
proc autoreg data=TS3.example35_2;
 m1: model delta1=t/dwprob;
 run;
Data TS3.example35_3;
set TS3.example35;
y1=406.35367+0.30541*t;
residual1=price-y1;
run;
Proc gplot data=TS3.example35_3; 
 plot price*t y1*t/overlay;
 run;
 plot residual1*t;
 run;
proc autoreg data=TS3.example35_3;
 m2: model residual1=t/dwprob;
 run;
ods graphics off;
ods html close;
ods listing;
