ods html; 
ods listing close; 
ods graphics on; 
Data figure55;
y=0;
y1=0;
e1=0;
e2=0;
do t=-50 to 200;
    if t=-50 then do;
        e=normal(0);
        y=1.5*y-0.5*y1+e-e1+0.25*e2;
        if t>0 then
        output;
        end;
   else if t=-49 then do;
       temp=y;
	   e1=e;
	   e=normal(0);
       y=1.5*y-0.5*y1+e-e1+0.25*e2;
       y1=temp;
       diff1=y-y1;
	   if t>0 then
       output;        
        end;
	else do;
         temp=y;
         e2=e1;
         e1=e;
	     e=normal(0);
         y=1.5*y-0.5*y1+e-e1+0.25*e2;
         y1=temp;
         diff1=y-y1;
		 if t>0 then
         output;        
		end;
 end;
drop temp;
run;
Proc gplot data=figure55; 
      symbol i=spline v=circle h=1.5; 
      plot y * t;
      title 'Time plot of Y=1.5Y1-0.5Y2+e-e1+0.25e2';
   run;
      symbol i=spline v=circle h=1.5; 
      plot diff1 * t;
      title 'Time plot of difference';
   run;
proc autoreg data=figure55;
 m1: model y=t/dw=12 dwprob;
 m2: model diff1=t/dw=12 dwprob;
 run;

ods graphics off;
ods html close;
ods listing;
