ods html; 
ods listing close; 
ods graphics on; 
libname TS4 'c:\Library_timeseries';

Data figure413;
 y=0;
 y1=0;
 do t=-50 to 100;
  e=normal(0);
   if t=-50 then do; 
     y=y-0.5*y1+e;
     if t>0 then output;
     end;
	 else do;
	      tem=y;
          y=1*y-0.5*y1+e;
          y1=tem;
		  y2=lag(y1);
		  y3=lag(y2);
         if t>0 then output;
	     end;
   end; 
   drop temp;
 run;

Proc gplot data=figure413; 
 symbol i=spline v=circle h=1.5; 
 plot y * t;
 title 'Plot of a series of AR(2) with (0.5,-0.5)';
 run;
  symbol i= v=circle h=1; 
  plot y * y1;
  title 'Scatter plot (y,y1)';
 run;
  symbol i= v=circle h=1; 
  plot y * y2;
  title 'Scatter plot (y,y2)';
run;
      symbol i= v=circle h=1; 
      plot y * y3;
      title 'Scatter plot (y,y3)';
run;
proc autoreg data=figure413;
   model y=t/dw=12 dwprob normal;
run;

ods graphics off;
ods html close;
ods listing;
